fix: Black Box stats ObjectId constructor requires 'new' keyword
Error: Class constructor ObjectId cannot be invoked without 'new'
Fix: Changed require('mongoose').Types.ObjectId() to new mongoose.Types.ObjectId()